package com.fbduel.entity;

// default package
// Generated Mar 11, 2011 1:46:14 AM by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int uid;

	public User() {
	}

	public User(int uid) {
		this.uid = uid;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

}
